'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.18444
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'このソース コードは Microsoft.VSDesigner、バージョン 4.0.30319.18444 によって自動生成されました。
'
Namespace WebReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="KanriServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class KanriService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistEnterOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistExitOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GateEnterOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GateExitOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetEnterPersonOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPersonInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPurposesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetRoomsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PutCreatedCardOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsThisAllowOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AllowEnterRoomOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CountEnteredPersonOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExistRoomOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListAllowRoomsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.GateManager.My.MySettings.Default.GateManager_WebReference_KanriService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistEnterCompleted As RegistEnterCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistExitCompleted As RegistExitCompletedEventHandler
        
        '''<remarks/>
        Public Event GateEnterCompleted As GateEnterCompletedEventHandler
        
        '''<remarks/>
        Public Event GateExitCompleted As GateExitCompletedEventHandler
        
        '''<remarks/>
        Public Event GetEnterPersonCompleted As GetEnterPersonCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPersonInfoCompleted As GetPersonInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPurposesCompleted As GetPurposesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetRoomsCompleted As GetRoomsCompletedEventHandler
        
        '''<remarks/>
        Public Event PutCreatedCardCompleted As PutCreatedCardCompletedEventHandler
        
        '''<remarks/>
        Public Event IsThisAllowCompleted As IsThisAllowCompletedEventHandler
        
        '''<remarks/>
        Public Event AllowEnterRoomCompleted As AllowEnterRoomCompletedEventHandler
        
        '''<remarks/>
        Public Event CountEnteredPersonCompleted As CountEnteredPersonCompletedEventHandler
        
        '''<remarks/>
        Public Event ExistRoomCompleted As ExistRoomCompletedEventHandler
        
        '''<remarks/>
        Public Event ListAllowRoomsCompleted As ListAllowRoomsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync()
            Me.HelloWorldAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal userState As Object)
            If (Me.HelloWorldOperationCompleted Is Nothing) Then
                Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
            End If
            Me.InvokeAsync("HelloWorld", New Object(-1) {}, Me.HelloWorldOperationCompleted, userState)
        End Sub
        
        Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
            If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistEnter", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistEnter(ByVal Person As PersonInfo) As String
            Dim results() As Object = Me.Invoke("RegistEnter", New Object() {Person})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistEnterAsync(ByVal Person As PersonInfo)
            Me.RegistEnterAsync(Person, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistEnterAsync(ByVal Person As PersonInfo, ByVal userState As Object)
            If (Me.RegistEnterOperationCompleted Is Nothing) Then
                Me.RegistEnterOperationCompleted = AddressOf Me.OnRegistEnterOperationCompleted
            End If
            Me.InvokeAsync("RegistEnter", New Object() {Person}, Me.RegistEnterOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistEnterOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistEnterCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistEnterCompleted(Me, New RegistEnterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistExit", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistExit(ByVal person As PersonInfo, ByVal RoomID As Integer) As String
            Dim results() As Object = Me.Invoke("RegistExit", New Object() {person, RoomID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistExitAsync(ByVal person As PersonInfo, ByVal RoomID As Integer)
            Me.RegistExitAsync(person, RoomID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistExitAsync(ByVal person As PersonInfo, ByVal RoomID As Integer, ByVal userState As Object)
            If (Me.RegistExitOperationCompleted Is Nothing) Then
                Me.RegistExitOperationCompleted = AddressOf Me.OnRegistExitOperationCompleted
            End If
            Me.InvokeAsync("RegistExit", New Object() {person, RoomID}, Me.RegistExitOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistExitOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistExitCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistExitCompleted(Me, New RegistExitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GateEnter", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GateEnter(ByVal person As PersonInfo, ByVal RoomID As Integer) As String
            Dim results() As Object = Me.Invoke("GateEnter", New Object() {person, RoomID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GateEnterAsync(ByVal person As PersonInfo, ByVal RoomID As Integer)
            Me.GateEnterAsync(person, RoomID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GateEnterAsync(ByVal person As PersonInfo, ByVal RoomID As Integer, ByVal userState As Object)
            If (Me.GateEnterOperationCompleted Is Nothing) Then
                Me.GateEnterOperationCompleted = AddressOf Me.OnGateEnterOperationCompleted
            End If
            Me.InvokeAsync("GateEnter", New Object() {person, RoomID}, Me.GateEnterOperationCompleted, userState)
        End Sub
        
        Private Sub OnGateEnterOperationCompleted(ByVal arg As Object)
            If (Not (Me.GateEnterCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GateEnterCompleted(Me, New GateEnterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GateExit", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GateExit(ByVal person As PersonInfo) As Boolean
            Dim results() As Object = Me.Invoke("GateExit", New Object() {person})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GateExitAsync(ByVal person As PersonInfo)
            Me.GateExitAsync(person, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GateExitAsync(ByVal person As PersonInfo, ByVal userState As Object)
            If (Me.GateExitOperationCompleted Is Nothing) Then
                Me.GateExitOperationCompleted = AddressOf Me.OnGateExitOperationCompleted
            End If
            Me.InvokeAsync("GateExit", New Object() {person}, Me.GateExitOperationCompleted, userState)
        End Sub
        
        Private Sub OnGateExitOperationCompleted(ByVal arg As Object)
            If (Not (Me.GateExitCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GateExitCompleted(Me, New GateExitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEnterPerson", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEnterPerson(ByVal CardID As Integer) As Boolean
            Dim results() As Object = Me.Invoke("GetEnterPerson", New Object() {CardID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEnterPersonAsync(ByVal CardID As Integer)
            Me.GetEnterPersonAsync(CardID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEnterPersonAsync(ByVal CardID As Integer, ByVal userState As Object)
            If (Me.GetEnterPersonOperationCompleted Is Nothing) Then
                Me.GetEnterPersonOperationCompleted = AddressOf Me.OnGetEnterPersonOperationCompleted
            End If
            Me.InvokeAsync("GetEnterPerson", New Object() {CardID}, Me.GetEnterPersonOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEnterPersonOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEnterPersonCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEnterPersonCompleted(Me, New GetEnterPersonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPersonInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPersonInfo(ByVal CardID As Integer) As PersonInfo
            Dim results() As Object = Me.Invoke("GetPersonInfo", New Object() {CardID})
            Return CType(results(0),PersonInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPersonInfoAsync(ByVal CardID As Integer)
            Me.GetPersonInfoAsync(CardID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPersonInfoAsync(ByVal CardID As Integer, ByVal userState As Object)
            If (Me.GetPersonInfoOperationCompleted Is Nothing) Then
                Me.GetPersonInfoOperationCompleted = AddressOf Me.OnGetPersonInfoOperationCompleted
            End If
            Me.InvokeAsync("GetPersonInfo", New Object() {CardID}, Me.GetPersonInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPersonInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPersonInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPersonInfoCompleted(Me, New GetPersonInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPurposes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPurposes() As String()
            Dim results() As Object = Me.Invoke("GetPurposes", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPurposesAsync()
            Me.GetPurposesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPurposesAsync(ByVal userState As Object)
            If (Me.GetPurposesOperationCompleted Is Nothing) Then
                Me.GetPurposesOperationCompleted = AddressOf Me.OnGetPurposesOperationCompleted
            End If
            Me.InvokeAsync("GetPurposes", New Object(-1) {}, Me.GetPurposesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPurposesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPurposesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPurposesCompleted(Me, New GetPurposesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRooms", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRooms() As RoomsInfo
            Dim results() As Object = Me.Invoke("GetRooms", New Object(-1) {})
            Return CType(results(0),RoomsInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetRoomsAsync()
            Me.GetRoomsAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetRoomsAsync(ByVal userState As Object)
            If (Me.GetRoomsOperationCompleted Is Nothing) Then
                Me.GetRoomsOperationCompleted = AddressOf Me.OnGetRoomsOperationCompleted
            End If
            Me.InvokeAsync("GetRooms", New Object(-1) {}, Me.GetRoomsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetRoomsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetRoomsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetRoomsCompleted(Me, New GetRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PutCreatedCard", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PutCreatedCard(ByVal CardID As Integer) As Boolean
            Dim results() As Object = Me.Invoke("PutCreatedCard", New Object() {CardID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PutCreatedCardAsync(ByVal CardID As Integer)
            Me.PutCreatedCardAsync(CardID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PutCreatedCardAsync(ByVal CardID As Integer, ByVal userState As Object)
            If (Me.PutCreatedCardOperationCompleted Is Nothing) Then
                Me.PutCreatedCardOperationCompleted = AddressOf Me.OnPutCreatedCardOperationCompleted
            End If
            Me.InvokeAsync("PutCreatedCard", New Object() {CardID}, Me.PutCreatedCardOperationCompleted, userState)
        End Sub
        
        Private Sub OnPutCreatedCardOperationCompleted(ByVal arg As Object)
            If (Not (Me.PutCreatedCardCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PutCreatedCardCompleted(Me, New PutCreatedCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsThisAllow", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsThisAllow(ByVal CardID As Integer, ByVal RoomID As Integer) As Boolean
            Dim results() As Object = Me.Invoke("IsThisAllow", New Object() {CardID, RoomID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub IsThisAllowAsync(ByVal CardID As Integer, ByVal RoomID As Integer)
            Me.IsThisAllowAsync(CardID, RoomID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsThisAllowAsync(ByVal CardID As Integer, ByVal RoomID As Integer, ByVal userState As Object)
            If (Me.IsThisAllowOperationCompleted Is Nothing) Then
                Me.IsThisAllowOperationCompleted = AddressOf Me.OnIsThisAllowOperationCompleted
            End If
            Me.InvokeAsync("IsThisAllow", New Object() {CardID, RoomID}, Me.IsThisAllowOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsThisAllowOperationCompleted(ByVal arg As Object)
            If (Not (Me.IsThisAllowCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsThisAllowCompleted(Me, New IsThisAllowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllowEnterRoom", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AllowEnterRoom(ByVal CardID As Integer, ByVal RoomID As Integer) As Boolean
            Dim results() As Object = Me.Invoke("AllowEnterRoom", New Object() {CardID, RoomID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AllowEnterRoomAsync(ByVal CardID As Integer, ByVal RoomID As Integer)
            Me.AllowEnterRoomAsync(CardID, RoomID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AllowEnterRoomAsync(ByVal CardID As Integer, ByVal RoomID As Integer, ByVal userState As Object)
            If (Me.AllowEnterRoomOperationCompleted Is Nothing) Then
                Me.AllowEnterRoomOperationCompleted = AddressOf Me.OnAllowEnterRoomOperationCompleted
            End If
            Me.InvokeAsync("AllowEnterRoom", New Object() {CardID, RoomID}, Me.AllowEnterRoomOperationCompleted, userState)
        End Sub
        
        Private Sub OnAllowEnterRoomOperationCompleted(ByVal arg As Object)
            If (Not (Me.AllowEnterRoomCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AllowEnterRoomCompleted(Me, New AllowEnterRoomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CountEnteredPerson", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CountEnteredPerson(ByVal RoomID As Integer) As Integer
            Dim results() As Object = Me.Invoke("CountEnteredPerson", New Object() {RoomID})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CountEnteredPersonAsync(ByVal RoomID As Integer)
            Me.CountEnteredPersonAsync(RoomID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CountEnteredPersonAsync(ByVal RoomID As Integer, ByVal userState As Object)
            If (Me.CountEnteredPersonOperationCompleted Is Nothing) Then
                Me.CountEnteredPersonOperationCompleted = AddressOf Me.OnCountEnteredPersonOperationCompleted
            End If
            Me.InvokeAsync("CountEnteredPerson", New Object() {RoomID}, Me.CountEnteredPersonOperationCompleted, userState)
        End Sub
        
        Private Sub OnCountEnteredPersonOperationCompleted(ByVal arg As Object)
            If (Not (Me.CountEnteredPersonCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CountEnteredPersonCompleted(Me, New CountEnteredPersonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExistRoom", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ExistRoom(ByVal CardID As Integer, ByVal RoomID As Integer) As Boolean
            Dim results() As Object = Me.Invoke("ExistRoom", New Object() {CardID, RoomID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExistRoomAsync(ByVal CardID As Integer, ByVal RoomID As Integer)
            Me.ExistRoomAsync(CardID, RoomID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExistRoomAsync(ByVal CardID As Integer, ByVal RoomID As Integer, ByVal userState As Object)
            If (Me.ExistRoomOperationCompleted Is Nothing) Then
                Me.ExistRoomOperationCompleted = AddressOf Me.OnExistRoomOperationCompleted
            End If
            Me.InvokeAsync("ExistRoom", New Object() {CardID, RoomID}, Me.ExistRoomOperationCompleted, userState)
        End Sub
        
        Private Sub OnExistRoomOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExistRoomCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExistRoomCompleted(Me, New ExistRoomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListAllowRooms", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListAllowRooms(ByVal CardID As Integer) As Integer()
            Dim results() As Object = Me.Invoke("ListAllowRooms", New Object() {CardID})
            Return CType(results(0),Integer())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListAllowRoomsAsync(ByVal CardID As Integer)
            Me.ListAllowRoomsAsync(CardID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListAllowRoomsAsync(ByVal CardID As Integer, ByVal userState As Object)
            If (Me.ListAllowRoomsOperationCompleted Is Nothing) Then
                Me.ListAllowRoomsOperationCompleted = AddressOf Me.OnListAllowRoomsOperationCompleted
            End If
            Me.InvokeAsync("ListAllowRooms", New Object() {CardID}, Me.ListAllowRoomsOperationCompleted, userState)
        End Sub
        
        Private Sub OnListAllowRoomsOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListAllowRoomsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListAllowRoomsCompleted(Me, New ListAllowRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PersonInfo
        
        Private cardIDField As Integer
        
        Private personNameField As String
        
        Private affiliationField As String
        
        Private purposeField As String
        
        Private destRoomsField() As Integer
        
        Private doseField As Integer
        
        Private registDateField As Date
        
        Private enterDateField As Date
        
        Private gateIDField As Integer
        
        Private registeredField As Boolean
        
        Private enteredField As Boolean
        
        Private langTypeField As String
        
        '''<remarks/>
        Public Property CardID() As Integer
            Get
                Return Me.cardIDField
            End Get
            Set
                Me.cardIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersonName() As String
            Get
                Return Me.personNameField
            End Get
            Set
                Me.personNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Affiliation() As String
            Get
                Return Me.affiliationField
            End Get
            Set
                Me.affiliationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Purpose() As String
            Get
                Return Me.purposeField
            End Get
            Set
                Me.purposeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DestRooms() As Integer()
            Get
                Return Me.destRoomsField
            End Get
            Set
                Me.destRoomsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Dose() As Integer
            Get
                Return Me.doseField
            End Get
            Set
                Me.doseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RegistDate() As Date
            Get
                Return Me.registDateField
            End Get
            Set
                Me.registDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EnterDate() As Date
            Get
                Return Me.enterDateField
            End Get
            Set
                Me.enterDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GateID() As Integer
            Get
                Return Me.gateIDField
            End Get
            Set
                Me.gateIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Registered() As Boolean
            Get
                Return Me.registeredField
            End Get
            Set
                Me.registeredField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Entered() As Boolean
            Get
                Return Me.enteredField
            End Get
            Set
                Me.enteredField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LangType() As String
            Get
                Return Me.langTypeField
            End Get
            Set
                Me.langTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RoomsInfo
        
        Private roomCountField As Integer
        
        Private roomIDField() As Integer
        
        Private roomNameField() As String
        
        Private roomNameEngField() As String
        
        Private gateIDField() As Integer
        
        '''<remarks/>
        Public Property RoomCount() As Integer
            Get
                Return Me.roomCountField
            End Get
            Set
                Me.roomCountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RoomID() As Integer()
            Get
                Return Me.roomIDField
            End Get
            Set
                Me.roomIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RoomName() As String()
            Get
                Return Me.roomNameField
            End Get
            Set
                Me.roomNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RoomNameEng() As String()
            Get
                Return Me.roomNameEngField
            End Get
            Set
                Me.roomNameEngField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GateID() As Integer()
            Get
                Return Me.gateIDField
            End Get
            Set
                Me.gateIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HelloWorldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub RegistEnterCompletedEventHandler(ByVal sender As Object, ByVal e As RegistEnterCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistEnterCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub RegistExitCompletedEventHandler(ByVal sender As Object, ByVal e As RegistExitCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistExitCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GateEnterCompletedEventHandler(ByVal sender As Object, ByVal e As GateEnterCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GateEnterCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GateExitCompletedEventHandler(ByVal sender As Object, ByVal e As GateExitCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GateExitCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetEnterPersonCompletedEventHandler(ByVal sender As Object, ByVal e As GetEnterPersonCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEnterPersonCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetPersonInfoCompletedEventHandler(ByVal sender As Object, ByVal e As GetPersonInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPersonInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PersonInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PersonInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetPurposesCompletedEventHandler(ByVal sender As Object, ByVal e As GetPurposesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPurposesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetRoomsCompletedEventHandler(ByVal sender As Object, ByVal e As GetRoomsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetRoomsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RoomsInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RoomsInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub PutCreatedCardCompletedEventHandler(ByVal sender As Object, ByVal e As PutCreatedCardCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PutCreatedCardCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub IsThisAllowCompletedEventHandler(ByVal sender As Object, ByVal e As IsThisAllowCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsThisAllowCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub AllowEnterRoomCompletedEventHandler(ByVal sender As Object, ByVal e As AllowEnterRoomCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AllowEnterRoomCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub CountEnteredPersonCompletedEventHandler(ByVal sender As Object, ByVal e As CountEnteredPersonCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CountEnteredPersonCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ExistRoomCompletedEventHandler(ByVal sender As Object, ByVal e As ExistRoomCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExistRoomCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ListAllowRoomsCompletedEventHandler(ByVal sender As Object, ByVal e As ListAllowRoomsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListAllowRoomsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer())
            End Get
        End Property
    End Class
End Namespace
